apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hgv27681
  namespace: hgv27681-beamline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hgv27681-beamline
  destination:
    name: argus
    namespace: hgv27681-beamline
  source:
    path: apps
    repoURL: https://github.com/gilesknap/hgv27681-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
